AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    c1c79669-6099-42cf-9acc-361ec5e80a4c:
      size:
        width: 750
        height: 250
      position:
        x: 150
        'y': 79
      z: 0
      embeds: []
Resources:
  VPC1:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.10.0.0/16
      Tags:
        - Key: Name
          Value: VPC-Name_1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c1c79669-6099-42cf-9acc-361ec5e80a4c
  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs:
            Ref: AWS::Region
      CidrBlock: 10.10.0.0/24
      VpcId:
        Ref: VPC1
      Tags:
      - Key: Name
        Value: "PublicSubnet01"
